### ISSUE TITLE
some error while generating the data

### ISSUE THREAD

**Issue by jeonggwanlee** [microsoft/dstc8-reddit-corpus#3]
Hi, 
I got some error while generating the data with script(python scripts/reddit.py generate)

I followed those description below.

Setup and Generation
    Modify run_dir in configs/config.prod.yaml to where you want all your data to be generated.
    Install the package with python setup.py install.
    Generate the data with python scripts/reddit.py generate.

### This is my error message.

> missing_checksums={'RC_2018-06.xz': '01778d656253b5497769eeab36c8610a64b6f271fbe4065cdc21f5841faee530', 'RC_2018-07.xz': 'e703b5b95005d655283ae7149ee775a31534402fa801705fc771c32eea874781', 'RC_2018-08.xz': 'b8939ecd280b48459c929c532eda923f3a2514db026175ed953a7956744c6003', 'RC_2018-10.xz': 'cadb242a4b5f166071effdd9adbc1d7a78c978d3622bc01cd0f20d3a4c269bd0'}
> delete_intermediate_data=False
ERROR: [pid 104057] Worker Worker(salt=761141828, workers=36, host=storm, username=jglee, pid=46329) failed    DownloadRawFile(date=2018-05, filetype=comments)
Traceback (most recent call last):
>  File "/home/jglee/anaconda3/envs/reddit/lib/python3.6/site-packages/luigi-2.8.8-py3.6.egg/luigi/worker.py", line 199, in run
>    new_deps = self._run_get_new_deps()
>  File "/home/jglee/anaconda3/envs/reddit/lib/python3.6/site-packages/luigi-2.8.8-py3.6.egg/luigi/worker.py", line 141, in _run_get_new_deps
>    task_gen = self.task.run()
>  File "/home/jglee/anaconda3/envs/reddit/lib/python3.6/site-packages/dstc8_reddit-0.1.0-py3.6.egg/dstc8_reddit/tasks/download.py", line 64, in run
>    raise RuntimeError(f"Checksums don't match for {'RC' if self.filetype == 'comments' else 'RS'}_{self.date}!")
> RuntimeError: Checksums don't match for RC_2018-05!
> ERROR: [pid 106791] Worker Worker(salt=761141828, workers=36, host=storm, username=jglee, pid=46329) failed    ZipDataset()
> Traceback (most recent call last):
>   File "/home/jglee/anaconda3/envs/reddit/lib/python3.6/site-packages/luigi-2.8.8-py3.6.egg/luigi/worker.py", line 199, in run
>     new_deps = self._run_get_new_deps()
>   File "/home/jglee/anaconda3/envs/reddit/lib/python3.6/site-packages/luigi-2.8.8-py3.6.egg/luigi/worker.py", line 141, in _run_get_new_deps
>     task_gen = self.task.run()
>   File "/home/jglee/anaconda3/envs/reddit/lib/python3.6/site-packages/dstc8_reddit-0.1.0-py3.6.egg/dstc8_reddit/tasks/packaging.py", line 138, in run
>    archive = ZipFile(zip_path, 'w', compression=ZIP_DEFLATED, compresslevel=9)
TypeError: __init__() got an unexpected keyword argument 'compresslevel'

===== Luigi Execution Summary =====

Scheduled 5085 tasks of which:
 \* 5084 ran successfully:
    \- 12 BuildDialogues(date=2017-11,2017-12,2018-01,2018-02,...)
    \- 24 DownloadRawFile(date=2017-11, filetype=comments) ...
    \- 12 FilterRawComments(date=2017-11,2017-12,2018-01,2018-02,...)
    \- 12 FilterRawSubmissions(date=2017-11,2017-12,2018-01,2018-02,...)
    \- 5000 MergeDialoguesOverDates(split=training, subreddit=1200isplenty) ...
    ...
\* 1 failed:
    \- 1 ZipDataset()

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

### And, This is my conda python library list.

(reddit) [jglee@storm dstc8-reddit-corpus]$ conda list
packages in environment at /home/jglee/anaconda3/envs/reddit:

> Name                    Version                   Build  Channel
> _libgcc_mutex             0.1                        main
> ca-certificates           2019.5.15                     1
> certifi                   2019.6.16                py36_1
> chardet                   3.0.4                    pypi_0    pypi
> click                     7.0                      pypi_0    pypi
> dataclasses               0.6                      pypi_0    pypi
> docutils                  0.15.2                   pypi_0    pypi
> idna                      2.8                      pypi_0    pypi
> libedit                   3.1.20181209         hc058e9b_0
> libffi                    3.2.1                hd88cf55_4
> libgcc-ng                 9.1.0                hdf63c60_0
> libstdcxx-ng              9.1.0                hdf63c60_0
> lockfile                  0.12.2                   pypi_0    pypi
> luigi                     2.8.8                    pypi_0    pypi
> ncurses                   6.1                  he6710b0_1
> numpy                     1.17.0                   pypi_0    pypi
> openssl                   1.0.2s               h7b6447c_0
> pip                       19.1.1                   py36_0
> pydantic                  0.32.1                   pypi_0    pypi
> python                    3.6.5                hc3d631a_2
> python-daemon             2.1.2                    pypi_0    pypi
> python-dateutil           2.8.0                    pypi_0    pypi
> python-rapidjson          0.8.0                    pypi_0    pypi
> readline                  7.0                  h7b6447c_5
> requests                  2.22.0                   pypi_0    pypi
> setuptools                41.0.1                   py36_0
> six                       1.12.0                   pypi_0    pypi
> sqlite                    3.29.0               h7b6447c_0
> tk                        8.6.8                hbc83047_0
> tornado                   4.5.3                    pypi_0    pypi
> urllib3                   1.25.3                   pypi_0    pypi
> wheel                     0.33.4                   py36_0
> xz                        5.2.4                h14c3975_4
> zlib                      1.2.11               h7b6447c_3

Is there anyone who knows a solution?

**Comment by aatkinson** [comment]
Ah sorry about this, the `compresslevel` parameter was adding in Python 3.7. I see you're running 3.6.
To work around this you can simply remove this offending argument from `tasks/packaging.py`.
I will remedy this issue on a subsequent PR
See https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile for details

**Comment by jeonggwanlee** [comment]
@aatkinson Thank you for replying.
I got it. I'll try it using Python 3.7.
