### ISSUE TITLE
Download script do not work - missing RS_* files

### ISSUE THREAD

**Issue by MichalPleban** [microsoft/dstc8-reddit-corpus#7]
The `reddit.py` script does not work anymore, because the submission files (with filenames starting with `RS`) are no longer available on `pushshift.io`. Therefore it is not possible to download and generate the data.

**Comment by rajbsk** [comment]
Hi, I am facing a similar issue. It would be great if the dataset is made available.
Thanks,
Rajdeep

**Comment by aatkinson** [comment]
This repository is no longer supported.
You can see what this [HuggingFace dataset has to offer](https://huggingface.co/datasets/roskoN/dstc8-reddit-corpus)
Or you can modify to code yourself to read .ZST files.
